trajectory:
  joint_names: [joint_1, joint_2, joint_3, joint_4, joint_5, joint_6]

  points:
    - positions:   [0.0, 0.0, 2.0, 0.0, 0.0, 0.0]
      velocities:  [0.0,  0.0, 0.0, 0.0, 0.0, 0.0]
      time_from_start: {sec: 2, nanosec: 0}
